# Quantumult X Ads - Web
#
# Raw:
# https://raw.githubusercontent.com/3kaiu/config/main/Profile/Ads/Web.conf

[rewrite_remote]
https://ghproxy.net/https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/Html/General.conf, tag=网页去广告, update-interval=86400, opt-parser=false, enabled=true
