# Quantumult X Ads - Ximalaya
#
# Raw:
# https://raw.githubusercontent.com/3kaiu/config/main/Profile/Ads/Ximalaya.conf

[rewrite_remote]
https://ghproxy.net/https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Ximalaya.conf, tag=喜马拉雅去广告, update-interval=86400, opt-parser=false, enabled=true
