# Quantumult X Ads - Zhihu
#
# Raw:
# https://raw.githubusercontent.com/3kaiu/config/main/Profile/Ads/Zhihu.conf

[rewrite_remote]
https://ghproxy.net/https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Zhihu.conf, tag=知乎去广告增强, update-interval=86400, opt-parser=false, enabled=true

[mitm]
hostname = *.zhimg.com, *.zhihu.com
